
services:
  - type: worker
    name: nova-colossyan-worker
    runtime: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python generate_video.py"
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: COLOSSYAN_API_KEY
        sync: false
      - key: QUESTION_UUID
        sync: false
